// <auto-generated />
using System;
using CRUDfaculta.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDfaculta.DataAcces.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20241103175732_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUDfaculta.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = 27,
                            BirthDate = new DateTime(1996, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Andrei Popescu",
                            PhoneNumber = "+40-712-123456"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Age = 33,
                            BirthDate = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Maria Ionescu",
                            PhoneNumber = "+40-712-234567"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Age = 38,
                            BirthDate = new DateTime(1985, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Ion Vasilescu",
                            PhoneNumber = "+40-712-345678"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Age = 31,
                            BirthDate = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Elena Dumitrescu",
                            PhoneNumber = "+40-712-456789"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Age = 35,
                            BirthDate = new DateTime(1988, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Alexandru Stan",
                            PhoneNumber = "+40-712-567890"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Age = 29,
                            BirthDate = new DateTime(1994, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Cristina Radulescu",
                            PhoneNumber = "+40-712-678901"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Age = 36,
                            BirthDate = new DateTime(1987, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Florin Georgescu",
                            PhoneNumber = "+40-712-789012"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Age = 28,
                            BirthDate = new DateTime(1995, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Ioana Mihai",
                            PhoneNumber = "+40-712-890123"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Age = 34,
                            BirthDate = new DateTime(1989, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Radu Marinescu",
                            PhoneNumber = "+40-712-901234"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Age = 30,
                            BirthDate = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Gabriela Olaru",
                            PhoneNumber = "+40-712-123789"
                        },
                        new
                        {
                            EmployeeId = 11,
                            Age = 43,
                            BirthDate = new DateTime(1980, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Mihai Dobre",
                            PhoneNumber = "+40-712-234890"
                        },
                        new
                        {
                            EmployeeId = 12,
                            Age = 32,
                            BirthDate = new DateTime(1991, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Ana Morar",
                            PhoneNumber = "+40-712-345901"
                        },
                        new
                        {
                            EmployeeId = 13,
                            Age = 37,
                            BirthDate = new DateTime(1986, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Dragos Barbu",
                            PhoneNumber = "+40-712-456012"
                        },
                        new
                        {
                            EmployeeId = 14,
                            Age = 39,
                            BirthDate = new DateTime(1984, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Diana Voinea",
                            PhoneNumber = "+40-712-567123"
                        },
                        new
                        {
                            EmployeeId = 15,
                            Age = 33,
                            BirthDate = new DateTime(1990, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "George Petrescu",
                            PhoneNumber = "+40-712-678234"
                        },
                        new
                        {
                            EmployeeId = 16,
                            Age = 28,
                            BirthDate = new DateTime(1995, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Adina Roman",
                            PhoneNumber = "+40-712-789345"
                        },
                        new
                        {
                            EmployeeId = 17,
                            Age = 30,
                            BirthDate = new DateTime(1993, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Vlad Neagu",
                            PhoneNumber = "+40-712-890456"
                        },
                        new
                        {
                            EmployeeId = 18,
                            Age = 31,
                            BirthDate = new DateTime(1992, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Alina Iacob",
                            PhoneNumber = "+40-712-901567"
                        },
                        new
                        {
                            EmployeeId = 19,
                            Age = 42,
                            BirthDate = new DateTime(1981, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Bogdan Tudor",
                            PhoneNumber = "+40-712-123678"
                        },
                        new
                        {
                            EmployeeId = 20,
                            Age = 34,
                            BirthDate = new DateTime(1989, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Anca Pavel",
                            PhoneNumber = "+40-712-234789"
                        },
                        new
                        {
                            EmployeeId = 21,
                            Age = 32,
                            BirthDate = new DateTime(1991, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Cosmin Stanescu",
                            PhoneNumber = "+40-712-345890"
                        },
                        new
                        {
                            EmployeeId = 22,
                            Age = 35,
                            BirthDate = new DateTime(1988, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Simona Moraru",
                            PhoneNumber = "+40-712-456901"
                        },
                        new
                        {
                            EmployeeId = 23,
                            Age = 44,
                            BirthDate = new DateTime(1979, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Lucian Pavel",
                            PhoneNumber = "+40-712-567012"
                        },
                        new
                        {
                            EmployeeId = 24,
                            Age = 29,
                            BirthDate = new DateTime(1994, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Raluca Balan",
                            PhoneNumber = "+40-712-678123"
                        },
                        new
                        {
                            EmployeeId = 25,
                            Age = 37,
                            BirthDate = new DateTime(1986, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Stefan Dumitru",
                            PhoneNumber = "+40-712-789234"
                        },
                        new
                        {
                            EmployeeId = 26,
                            Age = 31,
                            BirthDate = new DateTime(1992, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Daniela Ciobanu",
                            PhoneNumber = "+40-712-890345"
                        },
                        new
                        {
                            EmployeeId = 27,
                            Age = 40,
                            BirthDate = new DateTime(1983, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Paul Trifan",
                            PhoneNumber = "+40-712-901456"
                        },
                        new
                        {
                            EmployeeId = 28,
                            Age = 33,
                            BirthDate = new DateTime(1990, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Madalina Gabor",
                            PhoneNumber = "+40-712-123567"
                        },
                        new
                        {
                            EmployeeId = 29,
                            Age = 36,
                            BirthDate = new DateTime(1987, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Nicolae Stefan",
                            PhoneNumber = "+40-712-234678"
                        },
                        new
                        {
                            EmployeeId = 30,
                            Age = 30,
                            BirthDate = new DateTime(1993, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Laura Avram",
                            PhoneNumber = "+40-712-345789"
                        },
                        new
                        {
                            EmployeeId = 31,
                            Age = 39,
                            BirthDate = new DateTime(1984, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Sorin Radu",
                            PhoneNumber = "+40-712-456890"
                        },
                        new
                        {
                            EmployeeId = 32,
                            Age = 27,
                            BirthDate = new DateTime(1996, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Bianca Stancu",
                            PhoneNumber = "+40-712-567901"
                        },
                        new
                        {
                            EmployeeId = 33,
                            Age = 34,
                            BirthDate = new DateTime(1989, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Claudiu Ion",
                            PhoneNumber = "+40-712-678012"
                        },
                        new
                        {
                            EmployeeId = 34,
                            Age = 28,
                            BirthDate = new DateTime(1995, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Georgiana Pavel",
                            PhoneNumber = "+40-712-789123"
                        },
                        new
                        {
                            EmployeeId = 35,
                            Age = 32,
                            BirthDate = new DateTime(1991, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Mircea Olteanu",
                            PhoneNumber = "+40-712-890234"
                        },
                        new
                        {
                            EmployeeId = 36,
                            Age = 31,
                            BirthDate = new DateTime(1992, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Liliana Nastase",
                            PhoneNumber = "+40-712-901345"
                        },
                        new
                        {
                            EmployeeId = 37,
                            Age = 38,
                            BirthDate = new DateTime(1985, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Valentin Cernat",
                            PhoneNumber = "+40-712-123456"
                        },
                        new
                        {
                            EmployeeId = 38,
                            Age = 36,
                            BirthDate = new DateTime(1987, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Nicoleta Tanase",
                            PhoneNumber = "+40-712-234567"
                        },
                        new
                        {
                            EmployeeId = 39,
                            Age = 29,
                            BirthDate = new DateTime(1994, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Sergiu Grosu",
                            PhoneNumber = "+40-712-345678"
                        },
                        new
                        {
                            EmployeeId = 40,
                            Age = 37,
                            BirthDate = new DateTime(1986, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Monica Toma",
                            PhoneNumber = "+40-712-456789"
                        },
                        new
                        {
                            EmployeeId = 41,
                            Age = 35,
                            BirthDate = new DateTime(1988, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Andrei Marinescu",
                            PhoneNumber = "+40-712-567890"
                        },
                        new
                        {
                            EmployeeId = 42,
                            Age = 31,
                            BirthDate = new DateTime(1992, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Mirela Pavel",
                            PhoneNumber = "+40-712-678901"
                        },
                        new
                        {
                            EmployeeId = 43,
                            Age = 36,
                            BirthDate = new DateTime(1987, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Radu Dumitrescu",
                            PhoneNumber = "+40-712-789012"
                        },
                        new
                        {
                            EmployeeId = 44,
                            Age = 28,
                            BirthDate = new DateTime(1995, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Gabriela Moldovan",
                            PhoneNumber = "+40-712-890123"
                        },
                        new
                        {
                            EmployeeId = 45,
                            Age = 33,
                            BirthDate = new DateTime(1990, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Bogdan Ionescu",
                            PhoneNumber = "+40-712-901234"
                        },
                        new
                        {
                            EmployeeId = 46,
                            Age = 30,
                            BirthDate = new DateTime(1993, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Alina Popa",
                            PhoneNumber = "+40-712-123789"
                        },
                        new
                        {
                            EmployeeId = 47,
                            Age = 38,
                            BirthDate = new DateTime(1985, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Mihai Stan",
                            PhoneNumber = "+40-712-234890"
                        },
                        new
                        {
                            EmployeeId = 48,
                            Age = 32,
                            BirthDate = new DateTime(1991, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Oana Toma",
                            PhoneNumber = "+40-712-345901"
                        },
                        new
                        {
                            EmployeeId = 49,
                            Age = 37,
                            BirthDate = new DateTime(1986, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Cristian Gheorghe",
                            PhoneNumber = "+40-712-456012"
                        },
                        new
                        {
                            EmployeeId = 50,
                            Age = 34,
                            BirthDate = new DateTime(1989, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Elena Radu",
                            PhoneNumber = "+40-712-567123"
                        },
                        new
                        {
                            EmployeeId = 51,
                            Age = 31,
                            BirthDate = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "George Vasilescu",
                            PhoneNumber = "+40-712-678234"
                        },
                        new
                        {
                            EmployeeId = 52,
                            Age = 29,
                            BirthDate = new DateTime(1994, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Simona Neagu",
                            PhoneNumber = "+40-712-789345"
                        },
                        new
                        {
                            EmployeeId = 53,
                            Age = 35,
                            BirthDate = new DateTime(1988, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Lucian Enache",
                            PhoneNumber = "+40-712-890456"
                        },
                        new
                        {
                            EmployeeId = 54,
                            Age = 30,
                            BirthDate = new DateTime(1993, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Daniela Pop",
                            PhoneNumber = "+40-712-901567"
                        },
                        new
                        {
                            EmployeeId = 55,
                            Age = 32,
                            BirthDate = new DateTime(1991, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Florin Vasile",
                            PhoneNumber = "+40-712-123678"
                        },
                        new
                        {
                            EmployeeId = 56,
                            Age = 34,
                            BirthDate = new DateTime(1989, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Ana Dragan",
                            PhoneNumber = "+40-712-234789"
                        },
                        new
                        {
                            EmployeeId = 57,
                            Age = 28,
                            BirthDate = new DateTime(1995, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Rares Constantin",
                            PhoneNumber = "+40-712-345890"
                        },
                        new
                        {
                            EmployeeId = 58,
                            Age = 31,
                            BirthDate = new DateTime(1992, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Iulia Nistor",
                            PhoneNumber = "+40-712-456901"
                        },
                        new
                        {
                            EmployeeId = 59,
                            Age = 43,
                            BirthDate = new DateTime(1980, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Dorin Luca",
                            PhoneNumber = "+40-712-567012"
                        },
                        new
                        {
                            EmployeeId = 60,
                            Age = 29,
                            BirthDate = new DateTime(1994, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Diana Tudor",
                            PhoneNumber = "+40-712-678123"
                        },
                        new
                        {
                            EmployeeId = 61,
                            Age = 40,
                            BirthDate = new DateTime(1983, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Adrian Serban",
                            PhoneNumber = "+40-712-789234"
                        },
                        new
                        {
                            EmployeeId = 62,
                            Age = 33,
                            BirthDate = new DateTime(1990, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Raluca Petre",
                            PhoneNumber = "+40-712-890345"
                        },
                        new
                        {
                            EmployeeId = 63,
                            Age = 38,
                            BirthDate = new DateTime(1985, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Sorin Barbu",
                            PhoneNumber = "+40-712-901456"
                        },
                        new
                        {
                            EmployeeId = 64,
                            Age = 35,
                            BirthDate = new DateTime(1988, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Oana Radulescu",
                            PhoneNumber = "+40-712-123567"
                        },
                        new
                        {
                            EmployeeId = 65,
                            Age = 30,
                            BirthDate = new DateTime(1993, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Ion Balan",
                            PhoneNumber = "+40-712-234678"
                        },
                        new
                        {
                            EmployeeId = 66,
                            Age = 32,
                            BirthDate = new DateTime(1991, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Cristina Moraru",
                            PhoneNumber = "+40-712-345789"
                        },
                        new
                        {
                            EmployeeId = 67,
                            Age = 33,
                            BirthDate = new DateTime(1990, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Roxana Cojocaru",
                            PhoneNumber = "+40-712-456890"
                        },
                        new
                        {
                            EmployeeId = 68,
                            Age = 36,
                            BirthDate = new DateTime(1987, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Mihai Cernat",
                            PhoneNumber = "+40-712-567901"
                        },
                        new
                        {
                            EmployeeId = 69,
                            Age = 41,
                            BirthDate = new DateTime(1982, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Valentin Albu",
                            PhoneNumber = "+40-712-678012"
                        },
                        new
                        {
                            EmployeeId = 70,
                            Age = 28,
                            BirthDate = new DateTime(1995, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Gabriela Popescu",
                            PhoneNumber = "+40-712-789123"
                        },
                        new
                        {
                            EmployeeId = 71,
                            Age = 34,
                            BirthDate = new DateTime(1989, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Paul Mocanu",
                            PhoneNumber = "+40-712-890234"
                        },
                        new
                        {
                            EmployeeId = 72,
                            Age = 31,
                            BirthDate = new DateTime(1992, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Liliana Chirila",
                            PhoneNumber = "+40-712-901345"
                        },
                        new
                        {
                            EmployeeId = 73,
                            Age = 39,
                            BirthDate = new DateTime(1984, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Dragos Mihai",
                            PhoneNumber = "+40-712-123456"
                        },
                        new
                        {
                            EmployeeId = 74,
                            Age = 37,
                            BirthDate = new DateTime(1986, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Adriana Dumitrescu",
                            PhoneNumber = "+40-712-234567"
                        },
                        new
                        {
                            EmployeeId = 75,
                            Age = 32,
                            BirthDate = new DateTime(1991, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Bogdan Roman",
                            PhoneNumber = "+40-712-345678"
                        },
                        new
                        {
                            EmployeeId = 76,
                            Age = 29,
                            BirthDate = new DateTime(1994, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Elena Ciobanu",
                            PhoneNumber = "+40-712-456789"
                        },
                        new
                        {
                            EmployeeId = 77,
                            Age = 36,
                            BirthDate = new DateTime(1987, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "George Stanciu",
                            PhoneNumber = "+40-712-567890"
                        },
                        new
                        {
                            EmployeeId = 78,
                            Age = 30,
                            BirthDate = new DateTime(1993, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Silvia Gheorghita",
                            PhoneNumber = "+40-712-678901"
                        },
                        new
                        {
                            EmployeeId = 79,
                            Age = 42,
                            BirthDate = new DateTime(1981, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Ionut Avram",
                            PhoneNumber = "+40-712-789012"
                        },
                        new
                        {
                            EmployeeId = 80,
                            Age = 28,
                            BirthDate = new DateTime(1995, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Maria Dima",
                            PhoneNumber = "+40-712-890123"
                        },
                        new
                        {
                            EmployeeId = 81,
                            Age = 41,
                            BirthDate = new DateTime(1982, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Stefan Udrea",
                            PhoneNumber = "+40-712-901234"
                        },
                        new
                        {
                            EmployeeId = 82,
                            Age = 33,
                            BirthDate = new DateTime(1990, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Ileana Costea",
                            PhoneNumber = "+40-712-123789"
                        },
                        new
                        {
                            EmployeeId = 83,
                            Age = 34,
                            BirthDate = new DateTime(1989, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Dumitru Grigore",
                            PhoneNumber = "+40-712-234890"
                        },
                        new
                        {
                            EmployeeId = 84,
                            Age = 32,
                            BirthDate = new DateTime(1991, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Ana Irimia",
                            PhoneNumber = "+40-712-345901"
                        },
                        new
                        {
                            EmployeeId = 85,
                            Age = 38,
                            BirthDate = new DateTime(1985, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Ion Stan",
                            PhoneNumber = "+40-712-456012"
                        },
                        new
                        {
                            EmployeeId = 86,
                            Age = 35,
                            BirthDate = new DateTime(1988, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Bianca Lupu",
                            PhoneNumber = "+40-712-567123"
                        },
                        new
                        {
                            EmployeeId = 87,
                            Age = 31,
                            BirthDate = new DateTime(1992, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Nicolae Anghel",
                            PhoneNumber = "+40-712-678234"
                        },
                        new
                        {
                            EmployeeId = 88,
                            Age = 29,
                            BirthDate = new DateTime(1994, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Anca Albu",
                            PhoneNumber = "+40-712-789345"
                        },
                        new
                        {
                            EmployeeId = 89,
                            Age = 37,
                            BirthDate = new DateTime(1986, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Marius Badea",
                            PhoneNumber = "+40-712-890456"
                        },
                        new
                        {
                            EmployeeId = 90,
                            Age = 30,
                            BirthDate = new DateTime(1993, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Eugenia Chiriac",
                            PhoneNumber = "+40-712-901567"
                        },
                        new
                        {
                            EmployeeId = 91,
                            Age = 33,
                            BirthDate = new DateTime(1990, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Cosmin Raducanu",
                            PhoneNumber = "+40-712-123678"
                        },
                        new
                        {
                            EmployeeId = 92,
                            Age = 28,
                            BirthDate = new DateTime(1995, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Daniela Iliescu",
                            PhoneNumber = "+40-712-234789"
                        },
                        new
                        {
                            EmployeeId = 93,
                            Age = 40,
                            BirthDate = new DateTime(1983, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Petre Tomescu",
                            PhoneNumber = "+40-712-345890"
                        },
                        new
                        {
                            EmployeeId = 94,
                            Age = 32,
                            BirthDate = new DateTime(1991, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Lavinia Roman",
                            PhoneNumber = "+40-712-456901"
                        },
                        new
                        {
                            EmployeeId = 95,
                            Age = 36,
                            BirthDate = new DateTime(1987, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Stefan Fodor",
                            PhoneNumber = "+40-712-567012"
                        },
                        new
                        {
                            EmployeeId = 96,
                            Age = 30,
                            BirthDate = new DateTime(1993, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Ioana Pavel",
                            PhoneNumber = "+40-712-678123"
                        },
                        new
                        {
                            EmployeeId = 97,
                            Age = 35,
                            BirthDate = new DateTime(1988, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Octavian Dragu",
                            PhoneNumber = "+40-712-789234"
                        },
                        new
                        {
                            EmployeeId = 98,
                            Age = 31,
                            BirthDate = new DateTime(1992, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Nicoleta Banciu",
                            PhoneNumber = "+40-712-890345"
                        },
                        new
                        {
                            EmployeeId = 99,
                            Age = 33,
                            BirthDate = new DateTime(1990, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Darius Matei",
                            PhoneNumber = "+40-712-901456"
                        },
                        new
                        {
                            EmployeeId = 100,
                            Age = 28,
                            BirthDate = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Larisa Calin",
                            PhoneNumber = "+40-712-123567"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
